<?php

namespace CatalogBundle\Repository;

use CatalogBundle\Entity\Building;
use Doctrine\ORM\EntityRepository;

/**
 * BuildingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuildingRepository extends EntityRepository
{
    /**
     * @param Building $building
     * @return Building|null|object
     */
    public function insertUnique(Building $building)
    {
        $existed = $this->findOneBy([
            'address' => $building->getAddress(),
            'city' => $building->getCity()
        ]);

        if ($existed) {
            return $existed;
        }

        $this->_em->persist($building);
        $this->_em->flush();

        return $building;
    }

    /**
     * @param array $params
     * @param bool $isReturnQuery
     * @return array|\Doctrine\ORM\Query
     */
    public function findByParams(array $params = [], $isReturnQuery = false)
    {
        $qb = $this->_em->createQueryBuilder();

        $qb->select('building')->from('CatalogBundle:Building', 'building');

        if (isset($params['city'])) {
            $qb
                ->where('lower(building.city) LIKE lower(:city)')
                ->setParameter('city', '%' . $params['city'] . '%');
        }

        if ($isReturnQuery) {
            return $qb->getQuery();
        } else {
            return $qb->getQuery()->getResult();
        }
    }
}
