<?php

namespace CatalogBundle\Repository;

use Doctrine\ORM\EntityRepository;
use FOS\RestBundle\Util\Codes;
use Symfony\Component\Validator\Exception\InvalidArgumentException;

/**
 * FirmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FirmRepository extends EntityRepository
{
    /**
     * @return mixed
     */
    public function countAll()
    {
        $qb = $this->_em->createQueryBuilder();

        $qb->select('count(firm.id)');
        $qb->from('CatalogBundle:Firm', 'firm');

        return $qb->getQuery()->getSingleScalarResult();
    }

    /**
     * @param array $params
     * @param bool $isReturnQuery
     * @return array|\Doctrine\ORM\Query
     */
    public function findByParams(array $params = [], $isReturnQuery = false)
    {
        $qb = $this->_em->createQueryBuilder();

        $qb->select('firm')->from('CatalogBundle:Firm', 'firm');

        if (isset($params['name'])) {
            foreach (explode(' ', trim($params['name'])) as $namePartIndex => $namePart) {
                $qb
                    ->andWhere('lower(firm.name) LIKE lower(:namePart' . $namePartIndex . ')')
                    ->setParameter('namePart' . $namePartIndex, '%' . $namePart . '%');
            }
        }

        if (isset($params['building_id'])) {
            $qb
                ->andWhere('firm.building = :building_id')
                ->setParameter('building_id', $params['building_id']);
        }

        if (isset($params['city']) || isset($params['address']) || isset($params['point']) || isset($params['bound']) && isset($params['bound']['point1']) && isset($params['bound']['point2'])) {
            $qb->join('firm.building', 'building');
        }

        if (isset($params['city'])) {
            $qb
                ->andWhere('lower(building.city) LIKE lower(:city)')
                ->setParameter('city', '%' . $params['city'] . '%');
        }

        if (isset($params['address'])) {
            foreach (explode(' ', trim($params['address'])) as $addressPartIndex => $addressPart) {
                $qb
                    ->andWhere('lower(building.address) LIKE lower(:addressPart' . $addressPartIndex . ')')
                    ->setParameter('addressPart' . $addressPartIndex, '%' . $addressPart . '%');
            }
        }

        if (isset($params['rubric_name']) || isset($params['rubric_id'])) {
            $qb->join('firm.rubrics', 'rubrics');
        }

        if (isset($params['rubric_id'])) {
            $qb
                ->andWhere('rubrics.id = :rubric_id')
                ->setParameter('rubric_id', $params['rubric_id']);
        }

        if (isset($params['rubric_name'])) {
            foreach (explode(' ', trim($params['rubric_name'])) as $rubricPartIndex => $rubricPart) {
                $qb
                    ->andWhere('lower(rubrics.name) LIKE lower(:rubricPart' . $rubricPartIndex . ')')
                    ->setParameter('rubricPart' . $rubricPartIndex, '%' . $rubricPart . '%');
            }
        }

        if (isset($params['point']) || isset($params['bound']) && isset($params['bound']['point1']) && isset($params['bound']['point2'])) {
            $radius = 250;

            if (isset($params['radius'])) {
                $radius = intval($params['radius']);

                if ($radius < 1) {
                    throw new InvalidArgumentException('Too small radius!', Codes::HTTP_BAD_REQUEST);
                }

                if ($radius > 40000) {
                    throw new InvalidArgumentException('Too big radius!', Codes::HTTP_BAD_REQUEST);
                }
            }

            $R = 6371;  // earth's mean radius, km

            if (isset($params['bound']) && isset($params['bound']['point1']) && isset($params['bound']['point2'])) {
                list($maxLat, $minLng) = $this->getLatLng($params['bound']['point1']);

                list($minLat, $maxLng) = $this->getLatLng($params['bound']['point2']);

                $qb
                    ->andWhere('building.lat Between :minLat And :maxLat')
                    ->andWhere('building.lng Between :minLng And :maxLng')
                    ->setParameter('minLat', $minLat)
                    ->setParameter('minLng', $minLng)
                    ->setParameter('maxLat', $maxLat)
                    ->setParameter('maxLng', $maxLng);
            } else {
                list($lat, $lng) = $this->getLatLng($params['point']);

                // first-cut bounding box (in degrees)
                $maxLat = $lat + rad2deg($radius / $R);
                $minLat = $lat - rad2deg($radius / $R);

                // compensate for degrees longitude getting smaller with increasing latitude
                $maxLng = $lng + rad2deg($radius / $R / cos(deg2rad($lat)));
                $minLng = $lng - rad2deg($radius / $R / cos(deg2rad($lat)));

                $qb
                    //->addSelect('(acos(sin(radians(:lat))*sin(radians(building.lat)) + cos(radians(:lat))*cos(radians(building.lat))*cos(radians(building.lng)-radians(:lng))) * :R) AS distance')
                    ->andWhere('building.lat Between :minLat And :maxLat')
                    ->andWhere('building.lng Between :minLng And :maxLng')
                    ->andWhere('(acos(sin(radians(:lat))*sin(radians(building.lat)) + cos(radians(:lat))*cos(radians(building.lat))*cos(radians(building.lng)-radians(:lng))) * :R) <= :radius')
                    //->having('distance <= :radius')

                    ->setParameter('lat', $lat)
                    ->setParameter('lng', $lng)
                    ->setParameter('minLat', $minLat)
                    ->setParameter('minLng', $minLng)
                    ->setParameter('maxLat', $maxLat)
                    ->setParameter('maxLng', $maxLng)
                    ->setParameter('radius', $radius)
                    ->setParameter('R', $R);

                if (isset($params['sort']) && $params['sort'] == 'distance') {
                    $qb->orderBy('distance');
                }
            }
        }

        $qb->orderBy('firm.name');

        if ($isReturnQuery) {
            return $qb->getQuery();
        } else {
            return $qb->getQuery()->getResult();
        }
    }

    private function getLatLng($point)
    {
        $point = str_replace(" ", "", $point);

        if (!preg_match('/^[-+]?([1-8]?\d(\.\d+)?|90(\.0+)?),\s*[-+]?(180(\.0+)?|((1[0-7]\d)|([1-9]?\d))(\.\d+)?)$/', $point)) { //lat, lng check
            throw new InvalidArgumentException('Point "' . $point . '"" is not valid lat,lng!', Codes::HTTP_BAD_REQUEST);
        }

        return explode(',', $point);
    }
}
