<?php

namespace CatalogBundle\Repository;

use CatalogBundle\Entity\Phone;
use Doctrine\ORM\EntityRepository;

/**
 * PhoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhoneRepository extends EntityRepository
{
    public function insertUnique(Phone $phone)
    {
        $existed = $this->findOneBy(['number' => $phone->getNumber()]);

        if($existed){
            return $existed;
        }

        $this->_em->persist($phone);
        $this->_em->flush();

        return $phone;
    }
}
