<?php
namespace CatalogBundle\Repository;

use CatalogBundle\Entity\Rubric;
use Gedmo\Tree\Entity\Repository\ClosureTreeRepository;

/**
 * RubricRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RubricRepository extends ClosureTreeRepository
{
    public function insertUnique(Rubric $rubric)
    {
        $existed = $this->findOneBy(['name' => $rubric->getName()]);

        if($existed){
            return $existed;
        }

        $this->_em->persist($rubric);
        $this->_em->flush();

        return $rubric;
    }
}
