# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: $2y$12$J/1JetccFupcvi5rz4o/JuCMIL4M7tkDZ2AV3D0IABLbrBY0SCBUO
                        roles: 'ROLE_ADMIN'
                    user:
                        password: $2y$12$oCCSrR8.DmDoGeeA5jx61OqhlYmzbD/HeMW/Hk58UeMnp7mIkVLWe
                        roles: 'ROLE_USER'

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api.login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            form_login:
                check_path:               /api/login
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        api.doc:
            pattern:   ^/api/doc
            http_basic: ~
            stateless:  true
            logout:
                path:   /api/doc/logout
                target: /api/doc

        api:
            pattern:   ^/api
            stateless: true
            lexik_jwt: ~
            logout:
                path:   /api/logout

        main:
            anonymous: ~

    access_control:
        - { path: ^/api/login, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/api/doc, role: ROLE_ADMIN }

        - { path: ^/api, role: IS_AUTHENTICATED_FULLY }

